src/Entity/Apprenant.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ApprenantRepository")
 */
class Apprenant extends User
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    // /**
    //  * @ORM\Column(type="string", length=255)
    //  */
    // private $Email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Tel;

    /**
     * @ORM\Column(type="date")
     */
    private $DateNaissance;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Ville;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Git;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Avatar;

    



    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Reseau", mappedBy="Apprenant", orphanRemoval=true)
     */
    private $reseaux;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

  

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Offres", inversedBy="apprenant")
     */
    private $offres;

   

    /**
     * @ORM\OneToMany(targetEntity=PromoAppre::class, mappedBy="apprenant", orphanRemoval=true)
     */
    private $promoAppres;

    public function __construct()
    {

        $this->reseaux = new ArrayCollection();
        $this->promoAppres = new ArrayCollection();
    }

    public function getFullname()
    {
        return "{$this->Prenom} {$this->Nom}";
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    

    public function getTel(): ?string
    {
        return $this->Tel;
    }

    public function setTel(string $Tel): self
    {
        $this->Tel = $Tel;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->DateNaissance;
    }

    public function setDateNaissance(\DateTimeInterface $DateNaissance): self
    {
        $this->DateNaissance = $DateNaissance;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(string $Ville): self
    {
        $this->Ville = $Ville;

        return $this;
    }

    public function getGit(): ?string
    {
        return $this->Git;
    }

    public function setGit(?string $Git): self
    {
        $this->Git = $Git;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->Avatar;
    }

    public function setAvatar(?string $Avatar): self
    {
        $this->Avatar = $Avatar;

        return $this;
    }

    


    /**
     * @return Collection|Reseau[]
     */
    public function getReseaux(): Collection
    {
        return $this->reseaux;
    }

    public function addReseaux(Reseau $reseaux): self
    {
        if (!$this->reseaux->contains($reseaux)) {
            $this->reseaux[] = $reseaux;
            $reseaux->setApprenant($this);
        }

        return $this;
    }

    public function removeReseaux(Reseau $reseaux): self
    {
        if ($this->reseaux->contains($reseaux)) {
            $this->reseaux->removeElement($reseaux);
            // set the owning side to null (unless already changed)
            if ($reseaux->getApprenant() === $this) {
                $reseaux->setApprenant(null);
            }
        }

        return $this;
    }


    public function __toString()
    {
        return (string) strtoupper($this->Nom).' '.(string) strtoupper($this->Prenom);
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }


    public function getOffres(): ?Offres
    {
        return $this->offres;
    }

    public function setOffres(?Offres $offres): self
    {
        $this->offres = $offres;

        return $this;
    }

    

    /**
     * @return Collection|PromoAppre[]
     */
    public function getPromoAppres(): Collection
    {
        return $this->promoAppres;
    }

    public function addPromoAppre(PromoAppre $promoAppre): self
    {
        if (!$this->promoAppres->contains($promoAppre)) {
            $this->promoAppres[] = $promoAppre;
            $promoAppre->setApprenant($this);
        }

        return $this;
    }

    public function removePromoAppre(PromoAppre $promoAppre): self
    {
        if ($this->promoAppres->contains($promoAppre)) {
            $this->promoAppres->removeElement($promoAppre);
            // set the owning side to null (unless already changed)
            if ($promoAppre->getApprenant() === $this) {
                $promoAppre->setApprenant(null);
            }
        }

        return $this;
    }
}

src/Entity/Contacts.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ContactsRepository")
 */
class Contacts
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Tel;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Mobile;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Entreprise", inversedBy="Contact")
     */
    private $entreprise;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->Tel;
    }

    public function setTel(string $Tel): self
    {
        $this->Tel = $Tel;

        return $this;
    }

    public function getMobile(): ?string
    {
        return $this->Mobile;
    }

    public function setMobile(string $Mobile): self
    {
        $this->Mobile = $Mobile;

        return $this;
    }

    public function getEntreprise(): ?Entreprise
    {
        return $this->entreprise;
    }

    public function setEntreprise(?Entreprise $entreprise): self
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    public function getFullName()
    {
        return $this->Nom.' '.$this->Prenom;

    }
}

src/Entity/Formation.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FormationRepository")
 */
class Formation
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Intitule;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Duree;

    /**
     * @ORM\Column(type="integer")
     */
    private $NombreHeure;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Diplome;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Modalites;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Promotion", mappedBy="Formation")
     */
    private $promotions;

    public function __construct()
    {
        $this->promotions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIntitule(): ?string
    {
        return $this->Intitule;
    }

    public function setIntitule(string $Intitule): self
    {
        $this->Intitule = $Intitule;

        return $this;
    }

    public function getDuree(): ?string
    {
        return $this->Duree;
    }

    public function setDuree(string $Duree): self
    {
        $this->Duree = $Duree;

        return $this;
    }

    public function getNombreHeure(): ?int
    {
        return $this->NombreHeure;
    }

    public function setNombreHeure(int $NombreHeure): self
    {
        $this->NombreHeure = $NombreHeure;

        return $this;
    }

    public function getDiplome(): ?string
    {
        return $this->Diplome;
    }

    public function setDiplome(string $Diplome): self
    {
        $this->Diplome = $Diplome;

        return $this;
    }

    public function getModalites(): ?string
    {
        return $this->Modalites;
    }

    public function setModalites(?string $Modalites): self
    {
        $this->Modalites = $Modalites;

        return $this;
    }

    /**
     * @return Collection|Promotion[]
     */
    public function getPromotions(): Collection
    {
        return $this->promotions;
    }

    public function addPromotion(Promotion $promotion): self
    {
        if (!$this->promotions->contains($promotion)) {
            $this->promotions[] = $promotion;
            $promotion->setFormation($this);
        }

        return $this;
    }

    public function removePromotion(Promotion $promotion): self
    {
        if ($this->promotions->contains($promotion)) {
            $this->promotions->removeElement($promotion);
            // set the owning side to null (unless already changed)
            if ($promotion->getFormation() === $this) {
                $promotion->setFormation(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return (string) $this->Intitule;
    }


}

src/Entity/Offres.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OffresRepository")
 */
class Offres
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Intitule;

    /**
     * @ORM\Column(type="date")
     */
    private $DateDebut;

    /**
     * @ORM\Column(type="date")
     */
    private $DateFin;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $CahierDesCharges;

    

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Entreprise", inversedBy="offres")
     */
    private $Entreprise;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Apprenant", mappedBy="offres")
     */
    private $apprenant;

    public function __construct()
    {
        $this->apprenant = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIntitule(): ?string
    {
        return $this->Intitule;
    }

    public function setIntitule(string $Intitule): self
    {
        $this->Intitule = $Intitule;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->DateDebut;
    }

    public function setDateDebut(\DateTimeInterface $DateDebut): self
    {
        $this->DateDebut = $DateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->DateFin;
    }

    public function setDateFin(\DateTimeInterface $DateFin): self
    {
        $this->DateFin = $DateFin;

        return $this;
    }

    public function getCahierDesCharges(): ?string
    {
        return $this->CahierDesCharges;
    }

    public function setCahierDesCharges(?string $CahierDesCharges): self
    {
        $this->CahierDesCharges = $CahierDesCharges;

        return $this;
    }



    public function getEntreprise(): ?Entreprise
    {
        return $this->Entreprise;
    }

    public function setEntreprise(?Entreprise $Entreprise): self
    {
        $this->Entreprise = $Entreprise;

        return $this;
    }

    /**
     * @return Collection|Apprenant[]
     */
    public function getApprenant(): Collection
    {
        return $this->apprenant;
    }

    public function addApprenant(Apprenant $apprenant): self
    {
        if (!$this->apprenant->contains($apprenant)) {
            $this->apprenant[] = $apprenant;
            $apprenant->setOffres($this);
        }

        return $this;
    }

    public function removeApprenant(Apprenant $apprenant): self
    {
        if ($this->apprenant->contains($apprenant)) {
            $this->apprenant->removeElement($apprenant);
            // set the owning side to null (unless already changed)
            if ($apprenant->getOffres() === $this) {
                $apprenant->setOffres(null);
            }
        }

        return $this;
    }
}

src/Entity/Reseau.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ReseauRepository")
 */
class Reseau
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Lien;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Apprenant", inversedBy="reseaux")
     */
    private $Apprenant;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getLien(): ?string
    {
        return $this->Lien;
    }

    public function setLien(string $Lien): self
    {
        $this->Lien = $Lien;

        return $this;
    }

    public function getApprenant(): ?Apprenant
    {
        return $this->Apprenant;
    }

    public function setApprenant(?Apprenant $Apprenant): self
    {
        $this->Apprenant = $Apprenant;

        return $this;
    }

    public function __toString()
    {
        return (string) $this->getNom();
    }
}

templates/editor/apprenant/_collectionReseaux.html.twig
{% block _apprenant_Reseaux_widget %}

{{ form_widget(form) }}

<input type="hidden" id="widgets-counter" value="0">
<div class="form-group">
    <button type="button" class="btn btn-info" id="add-reseau">Ajouter un réseau</button>

</div>

{% endblock %}

{% block _apprenant_Reseaux_entry_row %}

{{ form_widget(form) }}

{% endblock %}




{% block _apprenant_Reseaux_entry_widget %}

<div class="form-group" id="{{id}}">
    <div class="row">
        <div class="col-10">
            <div class="row">

                <div class="col">
                    {{ form_widget(form.Nom) }}
                </div>
                <div class="col">
                    {{ form_widget(form.Lien) }}
                </div>
            </div>
        </div>
        <div class="col-2">
            <button type="button" data-action="delete" data-target="#{{id}}" class="btn btn-danger" id="delete-reseau">X</button>
        </div>
        
    </div>
</div>

{% endblock %}

templates/editor/apprenant/_nav_apprenant.html.twig
<nav class="navbar navbar-expand-lg navbar-light bg-light mt-3" >
    <a class="navbar-brand text-danger" href="#"><i class="fas fa-user-graduate fa-lg mr-3"></i></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item {% if p == 1 %}active{% endif %}">
                <a class="nav-link" href="{{ path('editor_apprenant_liste') }}">APPRENANTS</a>
            </li>
            <li class="nav-item {% if p == 2 %}active{% endif %}">
                <a class="nav-link " href="{{ path('editor_retard') }}">RETARDS</a>
            </li>
            <li class="nav-item {% if p == 3 %}active{% endif %}">
                <a class="nav-link " href="{{ path('editor_absence') }}">ABSENCES</a>
            </li>
            <li class="nav-item {% if p == 4 %}active{% endif %}">
                <a class="nav-link " href="{{ path('editor_competence') }}">COMPETENCES</a>
            </li>
            

        </ul>
    </div>
</nav>

templates/editor/apprenant/appreant_new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une Promotion{% endblock %}

{# insérer les sous form #}
{% form_theme form 'editor/apprenant/_collectionReseaux.html.twig' %}

{% block body %}
{% if app.user %}

    <style>
        .custom-file-input{
            opacity: .4;
        }
    </style>

    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-10 col-lg-9 col-md-8 ml-auto mb-5 mt-5">

                {% include "editor/apprenant/_nav_apprenant.html.twig" with {'p': 1} %}
                
                <div class="my-5">

                    <!-- afficher le formulaire d'ajout d'un apprenant -->
                    
                        <h4 class="btn btn-info btn-sm">Créer un apprenant</h4>
                        {{ form_start(form) }}
                        {{ form_widget(form) }}
                        
                        <button class="btn btn-outline-danger d-block ml-auto">Enregistrer</button>
                        {{ form_end(form) }}
                </div>      
            </div>
        </div>
    </div>

{% endif %}
{% endblock %}



{% block javascripts %}

    {# insérer les sous formulaires pour ajouter les réseaux sociaux #}
    <script src="{{asset('assets/js/collection.js')}}"></script>

{% endblock %}

templates/editor/apprenant/apprenant_edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification d'un apprenant{% endblock %}

{# insert embed form #}
{% form_theme form 'editor/apprenant/_collectionReseaux.html.twig' %}

{% block body %}

{% if app.user %}
<style>

    .custom-file-input {
        opacity: .4;
    }
</style>
    
    <div class="container-fluid ">
        <div class="row">
            <div class="col-xl-10 col-lg-9 col-md-8 ml-auto my-5">
                <!-- insert apprenant menu -->
                {% include "editor/apprenant/_nav_apprenant.html.twig" with {'p':1} %}

                <!-- display flash message -->
                <div class="my-5">
                    <h4 class="btn btn-info btn-sm">Modifier les infos de <strong>{{apprenant.fullname|upper}}</strong></h4>
                    <div>
                        <img width="64" class="ml-auto rounded" src="{{ asset('uploads/brochures/') }}{{apprenant.avatar}}" alt="">
                    </div>
                    {{ form_start(form) }}
                    {{ form_widget(form) }}
                    <button class="btn btn-outline-danger d-block ml-auto">Enregistrer</button>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
{% endif %}
{% endblock %}



{% block javascripts %}

<script src="{{asset('assets/js/collection.js')}}"></script>

{% endblock %}

templates/editor/apprenant/apprenant_show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une Promotion{% endblock %}

{% block body %}
{% if app.user %}

    <div class="container-fluid" >
        <div class="row">
            <div class="col-xl-10 col-lg-9 col-md-8 ml-auto mb-5 mt-5">
                <!-- insert apprenant nav -->
                {% include "editor/apprenant/_nav_apprenant.html.twig" with {'p':1} %}

                <div class="my-5">
                    <!-- un tableau d'un seul apprenant -->
                    <h4 class="btn btn-info btn-sm">Fiche apprenant</h4>
                    {% for apprenant in all %}
                    <div class="row">
                        <div class="col-md-4">
                                
                            <dl class="row">
                                <dt class="col-md-4"><img class="avatar" src="{{ asset('uploads/brochures/') }}{{apprenant.apprenant.avatar}}" alt=""></dt>
                                <dd class="col-md-8 pl-5">{{apprenant.apprenant.fullname|upper}}</dd>
                            </dl>
                        </div>
                        <div class="col-md-8 ">
                            <dl class="row">
                                <dt class="col-md-4">Git compte</dt>
                                <dd class="col-md-8">{{ apprenant.apprenant.git }}</dd>
                                <dt class="col-md-4">Email</dt>
                                <dd class="col-md-8">{{ apprenant.apprenant.email }}</dd>
                                <dt class="col-md-4">Adresse</dt>
                                <dd class="col-md-8">{{ apprenant.apprenant.adresse }}</dd>
                                <dt class="col-md-4">Ville</dt>
                                <dd class="col-md-8">{{ apprenant.apprenant.ville }}</dd>
                            </dl>
                        </div>
                    </div>
                    
                    {% endfor %}
                    <div>

                        <h6 class="show-liste btn-dark p-2">Formations</h6>
                        <table class="table table-hover">
                        
                            <thead>
                                <th scope="col">N°</th>
                                <th scope="col">Annee</th>
                                <th scope="col">Début</th>
                                <th scope="col">Fin</th>
                                <th scope="col">N° d'heures</th>
                                <th scope="col">Intitulé</th>
                                
                        
                            </thead>
                            <tbody >
                                {% set i = 0 %}
                                {% for promotion in all %}
                                    {% set i = i + 1 %}
                                   
                                    <tr>
                                        <td>{{i}}</td>
                                        <td>{{ promotion.promotion.annee }}</td>
                                        <td>{{ promotion.promotion.dateDebut|date("m/d/Y") }}</td>
                                        <td>{{ promotion.promotion.dateFin|date("m/d/Y") }}</td>
                                        <td>{{ promotion.promotion.formation.nombreHeure }}</td>
                                        <td>{{ promotion.promotion.formation.intitule }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        {# {% endif %} #}
                    </div>
                   
                    <div>
                        {# si l'apprenant a des réseux sociaux #}
                        {% for reseau in all %}
                            
                        
                        {% if reseau.apprenant.Reseaux|length > 0 %}
                        <h6 class="show-liste btn-dark p-2">Réseaux Sociaux</h6>
                        <table class="table table-hover">
                        
                            <thead>                       
                                <th scope="col">N°</th>
                                <th scope="col">Intitulé</th>
                                <th scope="col">Lien</th>
                            </thead>
                            <tbody>
                                {% set i = 0 %}
                                {% for reseau in reseau.apprenant.Reseaux %}
                                    {% set i = i + 1 %}
                                    <tr>
                                        <td>{{i}}</td>
                                        <td>{{reseau.nom}}</td>
                                        <td>{{reseau.lien}}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        {% endif %}
                        {% endfor %}
                    </div>

                    <div>
                        {# si l'apprenant a des retards #}
                        {% for retard in all %}
                        {% if retard.retards|length > 0 %}
                        <h6 class="show-liste btn-dark p-2">Retards</h6>
                        <table class="table table-hover">
                            <thead>              
                                <th scope="col" style="width: 25%;">N°</th>
                                <th scope="col" style="width: 25%;">Date</th>
                                <th scope="col" style="width: 25%;">N° d'heures</th>  
                                <th scope="col" style="width: 25%;">Justifié</th>
                            </thead>
                            <tbody>
                                {% set i = 0 %}
                                {% for retard in retard.retards %}
                                {% set i = i + 1 %}
                                <tr>
                                    <td>{{i}}</td>
                                    <td>{{retard.date|date('d/m/y')}}</td>
                                    <td>{{retard.nombreheure}}</td>
                                    <td>{{retard.justifie}}</td>
                                    
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        {% endif %}
                        {% endfor %}
                    </div>

                    <div> 
                        {# si l'apprenant a des absences #}
                        {% for absence in all %}
                        {% if absence.absences|length > 0 %}
                        <h6 class="show-liste btn-dark p-2">Absences</h6>
                        <table class="table table-hover">
                            <thead>
                                <th scope="col"style="width: 25%;">N°</th>
                                <th scope="col"style="width: 25%;">Date de début</th>
                                <th scope="col" style="width: 25%;">Date de fin</th>
                                <th scope="col" style="width: 25%;">Justifié</th>
                            </thead>
                            <tbody>
                                {% set i = 0 %}
                                {% for absence in absence.absences %}
                                {% set i = i + 1 %}
                                <tr>
                                    <td>{{i}}</td>
                                    <td>{{absence.dateDebut|date('d/m/y')}}</td>
                                    <td>{{absence.datefin|date('d/m/y')}}</td>
                                    <td>{{absence.justifie}}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        {% endif %}
                        {% endfor %}
                            
                    </div>

                    <div>
                        <h6 class="show-liste btn-dark p-2">Fiche Profil</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endif %}
{% endblock %}

{% block javascripts %}


{% endblock %}

templates/editor/apprenant/competence.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dashbord{% endblock %}

{% block body %}
{% if app.user %}


{# structure de la page 10 colonnes de largeur et alignée à droite #}
<div class="container-fluid">
    <div class="row">
        <div class="col-xl-10 col-lg-9 col-md-8 ml-auto mb-5 mt-5">
            {% include "editor/apprenant/_nav_apprenant.html.twig" with {"p": 4} %}
            {# page body #}
            {# {% include "template_parts/_nav_promotion.html.twig" %} #}
            <div class="my-5">
                <h4>ICI LES COMPTENCES</h4>
                
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}