src/Entity/Apprenant.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ApprenantRepository")
 */
class Apprenant extends User
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    // /**
    //  * @ORM\Column(type="string", length=255)
    //  */
    // private $Email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Tel;

    /**
     * @ORM\Column(type="date")
     */
    private $DateNaissance;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Ville;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Git;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Avatar;

    



    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Reseau", mappedBy="Apprenant", orphanRemoval=true)
     */
    private $reseaux;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

  

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Offres", inversedBy="apprenant")
     */
    private $offres;

   

    /**
     * @ORM\OneToMany(targetEntity=PromoAppre::class, mappedBy="apprenant", orphanRemoval=true)
     */
    private $promoAppres;

    public function __construct()
    {

        $this->reseaux = new ArrayCollection();
        $this->promoAppres = new ArrayCollection();
    }

    public function getFullname()
    {
        return "{$this->Prenom} {$this->Nom}";
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    

    public function getTel(): ?string
    {
        return $this->Tel;
    }

    public function setTel(string $Tel): self
    {
        $this->Tel = $Tel;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->DateNaissance;
    }

    public function setDateNaissance(\DateTimeInterface $DateNaissance): self
    {
        $this->DateNaissance = $DateNaissance;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(string $Ville): self
    {
        $this->Ville = $Ville;

        return $this;
    }

    public function getGit(): ?string
    {
        return $this->Git;
    }

    public function setGit(?string $Git): self
    {
        $this->Git = $Git;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->Avatar;
    }

    public function setAvatar(?string $Avatar): self
    {
        $this->Avatar = $Avatar;

        return $this;
    }

    


    /**
     * @return Collection|Reseau[]
     */
    public function getReseaux(): Collection
    {
        return $this->reseaux;
    }

    public function addReseaux(Reseau $reseaux): self
    {
        if (!$this->reseaux->contains($reseaux)) {
            $this->reseaux[] = $reseaux;
            $reseaux->setApprenant($this);
        }

        return $this;
    }

    public function removeReseaux(Reseau $reseaux): self
    {
        if ($this->reseaux->contains($reseaux)) {
            $this->reseaux->removeElement($reseaux);
            // set the owning side to null (unless already changed)
            if ($reseaux->getApprenant() === $this) {
                $reseaux->setApprenant(null);
            }
        }

        return $this;
    }


    public function __toString()
    {
        return (string) strtoupper($this->Nom).' '.(string) strtoupper($this->Prenom);
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }


    public function getOffres(): ?Offres
    {
        return $this->offres;
    }

    public function setOffres(?Offres $offres): self
    {
        $this->offres = $offres;

        return $this;
    }

    

    /**
     * @return Collection|PromoAppre[]
     */
    public function getPromoAppres(): Collection
    {
        return $this->promoAppres;
    }

    public function addPromoAppre(PromoAppre $promoAppre): self
    {
        if (!$this->promoAppres->contains($promoAppre)) {
            $this->promoAppres[] = $promoAppre;
            $promoAppre->setApprenant($this);
        }

        return $this;
    }

    public function removePromoAppre(PromoAppre $promoAppre): self
    {
        if ($this->promoAppres->contains($promoAppre)) {
            $this->promoAppres->removeElement($promoAppre);
            // set the owning side to null (unless already changed)
            if ($promoAppre->getApprenant() === $this) {
                $promoAppre->setApprenant(null);
            }
        }

        return $this;
    }
}

src/Entity/Offres.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OffresRepository")
 */
class Offres
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Intitule;

    /**
     * @ORM\Column(type="date")
     */
    private $DateDebut;

    /**
     * @ORM\Column(type="date")
     */
    private $DateFin;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $CahierDesCharges;

    

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Entreprise", inversedBy="offres")
     */
    private $Entreprise;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Apprenant", mappedBy="offres")
     */
    private $apprenant;

    public function __construct()
    {
        $this->apprenant = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIntitule(): ?string
    {
        return $this->Intitule;
    }

    public function setIntitule(string $Intitule): self
    {
        $this->Intitule = $Intitule;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->DateDebut;
    }

    public function setDateDebut(\DateTimeInterface $DateDebut): self
    {
        $this->DateDebut = $DateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->DateFin;
    }

    public function setDateFin(\DateTimeInterface $DateFin): self
    {
        $this->DateFin = $DateFin;

        return $this;
    }

    public function getCahierDesCharges(): ?string
    {
        return $this->CahierDesCharges;
    }

    public function setCahierDesCharges(?string $CahierDesCharges): self
    {
        $this->CahierDesCharges = $CahierDesCharges;

        return $this;
    }



    public function getEntreprise(): ?Entreprise
    {
        return $this->Entreprise;
    }

    public function setEntreprise(?Entreprise $Entreprise): self
    {
        $this->Entreprise = $Entreprise;

        return $this;
    }

    /**
     * @return Collection|Apprenant[]
     */
    public function getApprenant(): Collection
    {
        return $this->apprenant;
    }

    public function addApprenant(Apprenant $apprenant): self
    {
        if (!$this->apprenant->contains($apprenant)) {
            $this->apprenant[] = $apprenant;
            $apprenant->setOffres($this);
        }

        return $this;
    }

    public function removeApprenant(Apprenant $apprenant): self
    {
        if ($this->apprenant->contains($apprenant)) {
            $this->apprenant->removeElement($apprenant);
            // set the owning side to null (unless already changed)
            if ($apprenant->getOffres() === $this) {
                $apprenant->setOffres(null);
            }
        }

        return $this;
    }
}

src/Entity/Promotion.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PromotionRepository")
 */
class Promotion
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $Annee;

    /**
     * @ORM\Column(type="date")
     */
    private $DateDebut;

    /**
     * @ORM\Column(type="date")
     */
    private $DateFin;

    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Commentaires;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Formation", inversedBy="promotions")
     */
    private $Formation;


    /**
     * @ORM\OneToMany(targetEntity=PromoAppre::class, mappedBy="promotion",  orphanRemoval=true)
     */
    private $promoAppres;

    public function __construct()
    {

        $this->promoAppres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAnnee(): ?int
    {
        return $this->Annee;
    }

    public function setAnnee(int $Annee): self
    {
        $this->Annee = $Annee;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->DateDebut;
    }

    public function setDateDebut(\DateTimeInterface $DateDebut): self
    {
        $this->DateDebut = $DateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->DateFin;
    }

    public function setDateFin(\DateTimeInterface $DateFin): self
    {
        $this->DateFin = $DateFin;

        return $this;
    }



    public function getCommentaires(): ?string
    {
        return $this->Commentaires;
    }

    public function setCommentaires(?string $Commentaires): self
    {
        $this->Commentaires = $Commentaires;

        return $this;
    }

    public function getFormation(): ?Formation
    {
        return $this->Formation;
    }

    public function setFormation(?Formation $Formation): self
    {
        $this->Formation = $Formation;

        return $this;
    }

    

    public function __toString()
    {
        return (string) $this->Annee.' '.$this->Formation;
    }

    

    /**
     * @return Collection|PromoAppre[]
     */
    public function getPromoAppres(): Collection
    {
        return $this->promoAppres;
    }

    public function addPromoAppre(PromoAppre $promoAppre): self
    {
        if (!$this->promoAppres->contains($promoAppre)) {
            $this->promoAppres[] = $promoAppre;
            $promoAppre->setPromotion($this);
        }

        return $this;
    }

    public function removePromoAppre(PromoAppre $promoAppre): self
    {
        if ($this->promoAppres->contains($promoAppre)) {
            $this->promoAppres->removeElement($promoAppre);
            // set the owning side to null (unless already changed)
            if ($promoAppre->getPromotion() === $this) {
                $promoAppre->setPromotion(null);
            }
        }

        return $this;
    }

    
}

src/Entity/Retard.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RetardRepository")
 */
class Retard
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="integer")
     */
    private $nombreHeure;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $justifie;

    /**
     * @ORM\ManyToOne(targetEntity=PromoAppre::class, inversedBy="retards")
     * @ORM\JoinColumn(nullable=false)
     */
    private $PromoAppre;

  

    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getNombreHeure(): ?int
    {
        return $this->nombreHeure;
    }

    public function setNombreHeure(int $nombreHeure): self
    {
        $this->nombreHeure = $nombreHeure;

        return $this;
    }

    public function getJustifie(): ?string
    {
        return $this->justifie;
    }

    public function setJustifie(string $justifie): self
    {
        $this->justifie = $justifie;

        return $this;
    }

    public function getPromoAppre(): ?PromoAppre
    {
        return $this->PromoAppre;
    }

    public function setPromoAppre(?PromoAppre $PromoAppre): self
    {
        $this->PromoAppre = $PromoAppre;

        return $this;
    }


    
}

templates/editor/retard_absence/absence.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des absences{% endblock %}

{% block body %}
{% if app.user %}


<style>
    input {
        outline: none;
        border: none;
        border-bottom: 1px solid #777;
    }

    form input:focus {
        border-color: blue;


    }
</style>
<div class="container-fluid">
    <div class="row">
        <div class="col-xl-10 col-lg-9 col-md-8 ml-auto mb-3 mt-5">

            {% include "editor/apprenant/_nav_apprenant.html.twig" with {"p": 3} %}

            <div class="my-5">
                <!-- flash messages -->
                {% include "template_parts/_flash_message.html.twig" %}

                <h4 class="btn btn-info btn-sm">Liste des absences</h4>
                <!-- formulaire de recherche -->
                <form action="{{ path('editor_absence_chercher') }}" class="  ml-auto w-50 bg-info" style="position: relative;">
                    <input class="float-right form-group mr-2 " placeholder="chercher" type="text"
                        name="chercher_absence">
                    <button class=" badge badge-primary mr-2" style="position: absolute;right:0;cursor:pointer"
                        type="submit"><i class="fa fa-search "></i></button>
                </form>

                <table class="table table-hover">

                    <thead>

                        <th scope="col">Date de début</th>
                        <th scope="col">date de fin</th>
                        <th scope="col">Justifié</th>
                        <th scope="col">Apprenant</th>
                        <th scope="col">Promotion</th>

                        <th style="width: 15%;">Actions</th>
                    </thead>
                    <tbody>
                        {% for absence in absences %}
                        <tr>
                            <td>{{ absence.dateDebut|date("d/m/Y") }}</td>
                            <td>{{ absence.datefin|date("d/m/Y") }}</td>
                            <td>{{ absence.justifie }}</td>
                            <td>{{ absence.promoappre.apprenant.fullname|upper }}</td>
                            <td>{{ absence.promoappre.promotion.annee }}-{{ absence.promoappre.promotion.formation.intitule }}</td>
                        
                        
                        
                        
                            <!-- dans la dernère cellule, il y a trois liens: supprimer, modifier et visualiser -->
                            <td>
                                <!-- modifier un apprenant -->
                                <a class="btn btn-success btn-sm modif_promotion" title="modifier"
                                    href="{{ path('editor_absence_edit',{'id':absence.id}) }}"><i class="far fa-edit"></i></a>
                                    
                                <!-- supprimer un apprenant qui va afficher d'abord un message de confirmation -->
                                <a class="btn btn-danger btn-sm delete-record" title="supprimer" href="#"><i
                                        class="fas fa-trash-alt delete-promotion"></i></a>
                        
                        
                        
                        
                                <!-- div qui contient le message de confirmation afin de supprimer un apprenant -->
                                <div class="delete-confirm border bg-light  m-auto rounded p-3" style="position: absolute;top:40%;left:30%">
                                    <div>
                                        <h4>Vous êtes sûr de vouloir supprimer?</h4>
                                    </div>
                                    <div>
                                        <a class="btn btn-success non" href="">Non</a>
                                        <a class="btn btn-danger " href="{{ path('editor_absence_delete',{'id':absence.id}) }}">Oui</a>
                        
                                    </div>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}

                    </tbody>
                </table>
                <a class="btn btn-primary btn-sm" title="ajouter" href="{{ path('editor_absence_new') }}"><i
                        class="fas fa-plus-square"></i></a>

                <!-- pagination -->
                {% if pages == 0 %}
                {% set pages = 1 %}
                {% endif %}
                <nav class="">
                    <ul class="pagination pagination-sm justify-content-center">
                        <li class="page-item {% if page == 1 %}disabled{%  endif %}">
                            <a class="page-link" href="{{ path('editor_absence',{'page':page - 1}) }}" tabindex="-1">&laquo;</a>
                        </li>
                        {% for i in 1..pages %}
                        <li class="page-item {% if page == i %}active{% endif %}">
                            <a class="page-link" href="{{ path('editor_absence',{'page':i}) }}">{{i}} <span
                                    class="sr-only">(current)</span></a>
                        </li>
                        {% endfor %}
                
                        <li class="page-item {% if page == pages %}disabled{%  endif %}">
                            <a class="page-link" href="{{ path('editor_absence',{'page':page + 1}) }}">&raquo;</a>
                        </li>
                    </ul>
                </nav>

            </div>
            {# end body #}

        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/editor/retard_absence/absence_edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier un absence{% endblock %}

{% block body %}
{% if app.user %}


{# structure de la page 10 colonnes de largeur et alignée à droite #}
<div class="container-fluid">
    <div class="row">
        <div class="col-xl-10 col-lg-9 col-md-8 ml-auto mb-5 mt-5">
            {% include "editor/apprenant/_nav_apprenant.html.twig" with {"p": 3} %}
            
            
            <div class="my-5">
                
                <h4 class="btn btn-info btn-sm">Modifier un absence</h4>
                {{ form_start(form) }}
                {{ form_widget(form) }}
                <button class="btn btn-outline-danger d-block ml-auto">Enregistrer</button>
                {{ form_end(form) }}

            </div>
            {# end body #}

        </div>
    </div>
</div>
{% endif %}
{% endblock %}

{% block javascripts %}

<script>
    let $token = $('#absence__token')
    let $absence_promotion = $('#absence_promotion')
    let $absence_dateDebut = $('#absence_dateDebut')
    let $absence_dateFin = $('#absence_dateFin')

    $absence_promotion.change(function () {
        let $form = $(this).closest('form')
        let data = {}
        data[$token.attr('name')] = $token.val()
        data[$absence_promotion.attr('name')] = $absence_promotion.val()
        data[$absence_dateDebut.attr('name')] = $absence_dateDebut.val()
        data[$absence_dateFin.attr('name')] = $absence_dateFin.val()



        $.post($form.attr('action'), data).then(function (data) {
            $('#absence_apprenant').replaceWith(
                $(data).find('#absence_apprenant')
            )
        })
    })

</script>

{% endblock %}

templates/editor/retard_absence/absence_new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau absence{% endblock %}

{% block body %}
{% if app.user %}


{# structure de la page 10 colonnes de largeur et alignée à droite #}
<div class="container-fluid">
    <div class="row">
        <div class="col-xl-10 col-lg-9 col-md-8 ml-auto mb-5 mt-5">
            {% include "editor/apprenant/_nav_apprenant.html.twig" with {"p": 3} %}
            
            
            <div class="my-5">
                
                <h4 class="btn btn-info btn-sm">Ajouter un absence</h4>
                {{ form_start(form) }}
                {{ form_widget(form) }}
                <button class="btn btn-outline-danger d-block ml-auto">Enregistrer</button>
                {{ form_end(form) }}

            </div>
            {# end body #}

        </div>
    </div>
</div>
{% endif %}
{% endblock %}

{% block javascripts %}



{% endblock %}

templates/editor/retard_absence/retard.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des retards{% endblock %}

{% block body %}
{% if app.user %}


<style>
    input {
        outline: none;
        border: none;
        border-bottom: 1px solid #777;
    }

    form input:focus {
        border-color: blue;


    }
</style>
<div class="container-fluid">
    <div class="row">
        <div class="col-xl-10 col-lg-9 col-md-8 ml-auto mb-3 mt-5">

            {% include "editor/apprenant/_nav_apprenant.html.twig" with {"p": 2} %}

            <div class="my-5">
                <!-- flash messages -->
                {% include "template_parts/_flash_message.html.twig" %}

                <h4 class="btn btn-info btn-sm">Liste des retards</h4>
                <!-- formulaire de recherche -->
                <form action="{{ path('editor_retard_chercher') }}" class="  ml-auto w-50 bg-info" style="position: relative;">
                    <input class="float-right form-group mr-2 " placeholder="chercher" type="text"
                        name="chercher_retard">
                    <button class=" badge badge-primary mr-2" style="position: absolute;right:0;cursor:pointer"
                        type="submit"><i class="fa fa-search "></i></button>
                </form>
                
                <table class="table table-hover">
                
                    <thead>
                
                        <th scope="col">Date</th>
                        <th scope="col">N° d'heures</th>
                        <th scope="col">Justifié</th>
                        <th scope="col">Apprenant</th>
                        <th scope="col">Promotion</th>
                
                        <th style="width: 15%;">Actions</th>
                    </thead>
                    <tbody>
            
                        {% for retard in retards %}
                        <tr>
                            <td>{{ retard.date|date("d/m/Y") }}</td>
                            <td>{{ retard.nombreheure }}</td>
                            <td>{{ retard.justifie }}</td>
                            <td>{{ retard.promoAppre.apprenant.fullname|upper }}</td>
                            <td>{{ retard.promoAppre.promotion.annee }}-{{ retard.promoAppre.promotion.formation.intitule }}</td>
                        
                            
                        
                
                            <!-- dans la dernère cellule, il y a trois liens: supprimer, modifier et visualiser -->
                            <td>
                                
                                <!-- modifier un apprenant -->
                                <a class="btn btn-success btn-sm modif_promotion" title="modifier"
                                href="{{ path('editor_retard_edit',{'id':retard.id}) }}"><i class="far fa-edit"></i></a>
                                
                                <!-- supprimer un apprenant qui va afficher d'abord un message de confirmation -->
                                <a class="btn btn-danger btn-sm delete-record" title="supprimer" 
                                    href="#"><i class="fas fa-trash-alt delete-promotion"></i></a>
                                
                
                                <!-- div qui contient le message de confirmation afin de supprimer un apprenant -->
                                <div class="delete-confirm border bg-light  m-auto rounded p-3"
                                    style="position: absolute;top:40%;left:30%">
                                    <div>
                                        <h4>Vous êtes sûr de vouloir supprimer?</h4>
                                    </div>
                                    <div>
                                        <a class="btn btn-success non" href="">Non</a>
                                        <a class="btn btn-danger "
                                            href="{{ path('editor_retard_delete',{'id':retard.id}) }}">Oui</a>
                
                                    </div>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                
                    </tbody>
                </table>
                <a class="btn btn-primary btn-sm" title="ajouter" href="{{ path('editor_retard_new') }}"><i
                        class="fas fa-plus-square"></i></a>
                    
                <!-- pagination -->
                {% if pages == 0 %}
                {% set pages = 1 %}
                {% endif %}
                <nav class="">
                    <ul class="pagination pagination-sm justify-content-center">
                        <li class="page-item {% if page == 1 %}disabled{%  endif %}">
                            <a class="page-link" href="{{ path('editor_retard',{'page':page - 1}) }}" tabindex="-1">&laquo;</a>
                        </li>
                        {% for i in 1..pages %}
                        <li class="page-item {% if page == i %}active{% endif %}">
                            <a class="page-link" href="{{ path('editor_retard',{'page':i}) }}">{{i}} <span
                                    class="sr-only">(current)</span></a>
                        </li>
                        {% endfor %}
                
                        <li class="page-item {% if page == pages %}disabled{%  endif %}">
                            <a class="page-link" href="{{ path('editor_retard',{'page':page + 1}) }}">&raquo;</a>
                        </li>
                    </ul>
                </nav>

            </div>
            {# end body #}

        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/editor/retard_absence/retard_edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier un retard{% endblock %}

{% block body %}
{% if app.user %}


{# structure de la page 10 colonnes de largeur et alignée à droite #}
<div class="container-fluid">
    <div class="row">
        <div class="col-xl-10 col-lg-9 col-md-8 ml-auto mb-5 mt-5">
            {% include "editor/apprenant/_nav_apprenant.html.twig" with {"p": 2} %}
            
            
            <div class="my-5">
                <h4 class="btn btn-info btn-sm">Modifier un retard</h4>
                
                {{ form_start(form) }}
                {{ form_widget(form) }}
                <button class="btn btn-outline-danger d-block ml-auto">Enregistrer</button>
                {{ form_end(form) }}

            </div>
            {# end body #}

        </div>
    </div>
</div>
{% endif %}
{% endblock %}

{% block javascripts %}

{# <script>
    let $token = $('#retard__token')
    let $retard_promotion = $('#retard_promotion')
    let $retard_date = $('#retard_date')

    $retard_promotion.change(function () {
        let $form = $(this).closest('form')
        let data = {}
        data[$token.attr('name')] = $token.val()
        data[$retard_promotion.attr('name')] = $retard_promotion.val()
        data[$retard_date.attr('name')] = $retard_date.val()


        $.post($form.attr('action'), data).then(function (data) {
            $('#retard_apprenant').replaceWith(
                $(data).find('#retard_apprenant')
            )
        })
    })

</script> #}

{% endblock %}

templates/editor/retard_absence/retard_new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau retard{% endblock %}

{% block body %}
{% if app.user %}


{# structure de la page 10 colonnes de largeur et alignée à droite #}
<div class="container-fluid">
    <div class="row">
        <div class="col-xl-10 col-lg-9 col-md-8 ml-auto mb-5 mt-5">
            {% include "editor/apprenant/_nav_apprenant.html.twig" with {"p": 2} %}

            
            <div class="my-5">
                <h4 class="btn btn-info btn-sm">Ajouter un retard</h4>

                {{ form_start(form) }}
                {{ form_widget(form) }}
                <button class="btn btn-outline-danger d-block ml-auto">Enregistrer</button>
                {{ form_end(form) }}

            </div>
            {# end body #}

        </div>
    </div>
</div>
{% endif %}
{% endblock %}

{% block javascripts %}


{% endblock %}