src/Entity/Apprenant.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ApprenantRepository")
 */
class Apprenant extends User
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    // /**
    //  * @ORM\Column(type="string", length=255)
    //  */
    // private $Email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Tel;

    /**
     * @ORM\Column(type="date")
     */
    private $DateNaissance;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Ville;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Git;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Avatar;

    



    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Reseau", mappedBy="Apprenant", orphanRemoval=true)
     */
    private $reseaux;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

  

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Offres", inversedBy="apprenant")
     */
    private $offres;

   

    /**
     * @ORM\OneToMany(targetEntity=PromoAppre::class, mappedBy="apprenant", orphanRemoval=true)
     */
    private $promoAppres;

    public function __construct()
    {

        $this->reseaux = new ArrayCollection();
        $this->promoAppres = new ArrayCollection();
    }

    public function getFullname()
    {
        return "{$this->Prenom} {$this->Nom}";
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    

    public function getTel(): ?string
    {
        return $this->Tel;
    }

    public function setTel(string $Tel): self
    {
        $this->Tel = $Tel;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->DateNaissance;
    }

    public function setDateNaissance(\DateTimeInterface $DateNaissance): self
    {
        $this->DateNaissance = $DateNaissance;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(string $Ville): self
    {
        $this->Ville = $Ville;

        return $this;
    }

    public function getGit(): ?string
    {
        return $this->Git;
    }

    public function setGit(?string $Git): self
    {
        $this->Git = $Git;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->Avatar;
    }

    public function setAvatar(?string $Avatar): self
    {
        $this->Avatar = $Avatar;

        return $this;
    }

    


    /**
     * @return Collection|Reseau[]
     */
    public function getReseaux(): Collection
    {
        return $this->reseaux;
    }

    public function addReseaux(Reseau $reseaux): self
    {
        if (!$this->reseaux->contains($reseaux)) {
            $this->reseaux[] = $reseaux;
            $reseaux->setApprenant($this);
        }

        return $this;
    }

    public function removeReseaux(Reseau $reseaux): self
    {
        if ($this->reseaux->contains($reseaux)) {
            $this->reseaux->removeElement($reseaux);
            // set the owning side to null (unless already changed)
            if ($reseaux->getApprenant() === $this) {
                $reseaux->setApprenant(null);
            }
        }

        return $this;
    }


    public function __toString()
    {
        return (string) strtoupper($this->Nom).' '.(string) strtoupper($this->Prenom);
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }


    public function getOffres(): ?Offres
    {
        return $this->offres;
    }

    public function setOffres(?Offres $offres): self
    {
        $this->offres = $offres;

        return $this;
    }

    

    /**
     * @return Collection|PromoAppre[]
     */
    public function getPromoAppres(): Collection
    {
        return $this->promoAppres;
    }

    public function addPromoAppre(PromoAppre $promoAppre): self
    {
        if (!$this->promoAppres->contains($promoAppre)) {
            $this->promoAppres[] = $promoAppre;
            $promoAppre->setApprenant($this);
        }

        return $this;
    }

    public function removePromoAppre(PromoAppre $promoAppre): self
    {
        if ($this->promoAppres->contains($promoAppre)) {
            $this->promoAppres->removeElement($promoAppre);
            // set the owning side to null (unless already changed)
            if ($promoAppre->getApprenant() === $this) {
                $promoAppre->setApprenant(null);
            }
        }

        return $this;
    }
}

src/Entity/Contacts.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ContactsRepository")
 */
class Contacts
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Tel;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Mobile;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Entreprise", inversedBy="Contact")
     */
    private $entreprise;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->Tel;
    }

    public function setTel(string $Tel): self
    {
        $this->Tel = $Tel;

        return $this;
    }

    public function getMobile(): ?string
    {
        return $this->Mobile;
    }

    public function setMobile(string $Mobile): self
    {
        $this->Mobile = $Mobile;

        return $this;
    }

    public function getEntreprise(): ?Entreprise
    {
        return $this->entreprise;
    }

    public function setEntreprise(?Entreprise $entreprise): self
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    public function getFullName()
    {
        return $this->Nom.' '.$this->Prenom;

    }
}

src/Entity/Formation.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FormationRepository")
 */
class Formation
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Intitule;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Duree;

    /**
     * @ORM\Column(type="integer")
     */
    private $NombreHeure;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Diplome;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Modalites;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Promotion", mappedBy="Formation")
     */
    private $promotions;

    public function __construct()
    {
        $this->promotions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIntitule(): ?string
    {
        return $this->Intitule;
    }

    public function setIntitule(string $Intitule): self
    {
        $this->Intitule = $Intitule;

        return $this;
    }

    public function getDuree(): ?string
    {
        return $this->Duree;
    }

    public function setDuree(string $Duree): self
    {
        $this->Duree = $Duree;

        return $this;
    }

    public function getNombreHeure(): ?int
    {
        return $this->NombreHeure;
    }

    public function setNombreHeure(int $NombreHeure): self
    {
        $this->NombreHeure = $NombreHeure;

        return $this;
    }

    public function getDiplome(): ?string
    {
        return $this->Diplome;
    }

    public function setDiplome(string $Diplome): self
    {
        $this->Diplome = $Diplome;

        return $this;
    }

    public function getModalites(): ?string
    {
        return $this->Modalites;
    }

    public function setModalites(?string $Modalites): self
    {
        $this->Modalites = $Modalites;

        return $this;
    }

    /**
     * @return Collection|Promotion[]
     */
    public function getPromotions(): Collection
    {
        return $this->promotions;
    }

    public function addPromotion(Promotion $promotion): self
    {
        if (!$this->promotions->contains($promotion)) {
            $this->promotions[] = $promotion;
            $promotion->setFormation($this);
        }

        return $this;
    }

    public function removePromotion(Promotion $promotion): self
    {
        if ($this->promotions->contains($promotion)) {
            $this->promotions->removeElement($promotion);
            // set the owning side to null (unless already changed)
            if ($promotion->getFormation() === $this) {
                $promotion->setFormation(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return (string) $this->Intitule;
    }


}

src/Entity/Offres.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OffresRepository")
 */
class Offres
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Intitule;

    /**
     * @ORM\Column(type="date")
     */
    private $DateDebut;

    /**
     * @ORM\Column(type="date")
     */
    private $DateFin;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $CahierDesCharges;

    

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Entreprise", inversedBy="offres")
     */
    private $Entreprise;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Apprenant", mappedBy="offres")
     */
    private $apprenant;

    public function __construct()
    {
        $this->apprenant = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIntitule(): ?string
    {
        return $this->Intitule;
    }

    public function setIntitule(string $Intitule): self
    {
        $this->Intitule = $Intitule;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->DateDebut;
    }

    public function setDateDebut(\DateTimeInterface $DateDebut): self
    {
        $this->DateDebut = $DateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->DateFin;
    }

    public function setDateFin(\DateTimeInterface $DateFin): self
    {
        $this->DateFin = $DateFin;

        return $this;
    }

    public function getCahierDesCharges(): ?string
    {
        return $this->CahierDesCharges;
    }

    public function setCahierDesCharges(?string $CahierDesCharges): self
    {
        $this->CahierDesCharges = $CahierDesCharges;

        return $this;
    }



    public function getEntreprise(): ?Entreprise
    {
        return $this->Entreprise;
    }

    public function setEntreprise(?Entreprise $Entreprise): self
    {
        $this->Entreprise = $Entreprise;

        return $this;
    }

    /**
     * @return Collection|Apprenant[]
     */
    public function getApprenant(): Collection
    {
        return $this->apprenant;
    }

    public function addApprenant(Apprenant $apprenant): self
    {
        if (!$this->apprenant->contains($apprenant)) {
            $this->apprenant[] = $apprenant;
            $apprenant->setOffres($this);
        }

        return $this;
    }

    public function removeApprenant(Apprenant $apprenant): self
    {
        if ($this->apprenant->contains($apprenant)) {
            $this->apprenant->removeElement($apprenant);
            // set the owning side to null (unless already changed)
            if ($apprenant->getOffres() === $this) {
                $apprenant->setOffres(null);
            }
        }

        return $this;
    }
}

templates/editor/dashbord.html.twig
{% extends 'base.html.twig'  %}

{% block title %}Dashbord{% endblock %}

{% block body %}
<style>
    .bar{
        height: 150px;
        box-shadow: 5px 7px 25px #999;
        border-radius: 5px;
        padding: 10px;
    }
    .col a{
        text-decoration: none;
    }
</style>
{# structure de la page 10 colonnes de largeur et alignée à droite #}
<div class="container-fluid">
    <div class="row">
        <div class="col-xl-10 col-lg-9 col-md-8 ml-auto mb-5 mt-5">
            
            {# page body #}

            <div class="container mt-4">
                {# first line with title and icon #}
                <div class="row my-1">
                    <i class="fas fa-home text-danger fa-lg mr-3" style="font-size:32"></i> <p class="badge badge-danger">Tableau de bord</p>
                </div>
                {# second line, number of promotion, training, learner and partner #}
                <div class="row mt-5  text-light"  >
                    <div class="col p-1 text-center">
                        <a class="text-light" href="{{ path('admin_utilisateur') }}">
                            <div class=" bar alert-primary">
                                <i class="fas fa-users h1"></i>
                                <h2>Utilisateurs</h2>
                                <h3>{{ countUser }}</h3>
                            </div>
                        </a>
                    </div>
                    <div class="col p-1 text-center">
                        <a class="text-light" href="{{ path('editor_promo_liste') }}">
                            <div class=" bar alert-secondary">
                                <i class="fas fa-certificate h1"></i>
                                <h3>Promotions</h3>
                                <h3>{{ countPromotion }}</h3>
                            </div>
                        </a>
                    </div>
                    <div class="col  p-1 text-center">
                        <a class="text-light" href="{{ path('editor_formation') }}">
                            <div class="alert-light bar">
                                <i class="fas fa-laptop-code h1"></i>
                                <h2>Formations</h2>
                                <h3>{{ countFormation }}</h3>
                            </div>
                        </a>
                    </div>
                    <div class="col  p-1 text-center">
                        <a class="text-light" href="{{ path('editor_apprenant_liste') }}">
                            <div class="alert-success bar">
                                <i class="fas fa-user-graduate h1"></i>
                                <h2>Apprenants</h2>
                                <h3>{{ countApprenant }}</h3>
                            </div>
                        </a>
                    </div>
                   
                </div>

                <div class="row my-1 text-light">
                    <div class="col p-1 text-center">
                        <a class="text-light" href=""></a>
                            <div class="alert-warning bar">
                                <i class="far fa-handshake h1"></i>
                                <h2>Partenaires</h2>
                                <h3>N°</h3>
                            </div>
                        </div>
                    
                    <div class="col p-1 text-center">
                        <a class="text-light" href="{{ path('editor_entreprise') }}">
                            <div class="alert-dark bar">
                                <i class="fas fa-chart-line h1"></i>
                                <h2>Entreprises</h2>
                                <h3>{{ countEntreprise }}</h3>
                            </div>
                        </a>
                    </div>
                    <div class="col p-1 text-center">
                        <a class="text-light" href="{{ path('editor_offre') }}">
                            <div class="alert-info bar">
                                <i class="fas fa-toolbox h1"></i>
                                <h2>Stages</h2>
                                <h3>{{ countOffres }}</h3>
                            </div>
                        </a>
                    </div>
                    <div class="col p-1 text-center">
                        <a class="text-light" href="">
                            <div class="alert-danger bar">
                                <i class="fas fa-phone-alt h1"></i>
                                <h2>Contacts</h2>
                                <h3>{{countContact}}</h3>
                            </div>
                        </a>
                    </div>
                </div>
                {# third line: details of all #}
                {# <div class="row my-1 text-light">
                    <div class="col p-1">
                        <div class="bg-info p-2 rounded">
                            <h2>Apprenants</h2>
                            <table class="table">
                                <thead>
                                    <th scope="col">Nom et Prénom</th>
                                    <th scope="col">Date de naissance</th>
                                    <th scope="col">Email</th>
                                    <th scope="col">Tel</th>
                                </thead>
                                {% for apprenant in apprenants %}
                                <tr>
                                    <td><a class="text-light"
                                            href="{{ path('editor_apprenant_show',{'id':apprenant.id}) }}">{{apprenant.nom|upper}}
                                            {{apprenant.prenom|upper}}</a></td>
                                    <td><a class="text-light"
                                            href="{{ path('editor_apprenant_show',{'id':apprenant.id}) }}">{{ apprenant.dateNaissance|date('d/m/Y') }}
                                    </a></td>
                                    <td><a class="text-light"
                                            href="{{ path('editor_apprenant_show',{'id':apprenant.id}) }}">{{ apprenant.email }}</a></td>
                                    
                                    <td><a class="text-light"
                                            href="{{ path('editor_apprenant_show',{'id':apprenant.id}) }}"></a>{{ apprenant.tel }}</td>
                                </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                </div>
                <div class="row my-1 text-light">
                    <div class="col p-1">
                        <div class="bg-secondary p-2 rounded" id="promotion">
                            <h2>Promotions</h2>
                            <table class="table ">
                                <thead>
                                    <th scope="col">Année</th>
                                    <th scope="col">Début</th>
                                    <th scope="col">Fin</th>
                                    <th scope="col">Formation</th>
                                    <th scope="col">N° Apprenants</th>
                                </thead>
                                    {% for promotion in promotions %}
                                    <tr>
                                            <td><a class="text-light" href="{{ path('editor_promo_show',{'id':promotion.id}) }}">{{promotion.annee}}</a></td>
                                            <td><a class="text-light" href="{{ path('editor_promo_show',{'id':promotion.id}) }}">{{promotion.dateDebut|date('d/m/Y')}}</a></td>
                                            <td><a class="text-light" href="{{ path('editor_promo_show',{'id':promotion.id}) }}">{{promotion.dateFin|date('d/m/Y')}}</a></td>
                                            <td><a class="text-light" href="{{ path('editor_promo_show',{'id':promotion.id}) }}">{{promotion.formation.intitule}}</a></td>
                                            <td><a class="text-light" href="{{ path('editor_promo_show',{'id':promotion.id}) }}">{{promotion.apprenants|length}}</a></td>
                                        </tr>
                                    {% endfor %}
                            </table>
                        </div>
                    </div>
                </div>
                <div class="row my-1 text-light">
                    <div class="col p-1">
                        <div class="bg-success p-2 rounded" id="formation">
                            <h2>Formations</h2>
                            <table class="table">
                                <thead>
                                    <th scope="col">Intitulé</th>
                                    <th scope="col">Diplôme</th>
                                    <th scope="col">Durée</th>
                                    <th scope="col">N° d'heures</th>
                                </thead>
                                    {% for formation in formations %}
                                        <tr>
                                            <td><a class="text-light" href="{{ path('editor_formation',{'id':formation.id}) }}">{{formation.intitule}}</a></td>
                                            <td><a class="text-light" href="{{ path('editor_formation',{'id':formation.id}) }}">{{formation.diplome}}</a></td>
                                            <td><a class="text-light" href="{{ path('editor_formation',{'id':formation.id}) }}">{{formation.duree}}</a></td>
                                            <td><a class="text-light" href="{{ path('editor_formation',{'id':formation.id}) }}">{{formation.nombreHeure}}</a></td>
                                        </tr>
                                    {% endfor %}
                            </table>
                        </div>
                    </div>
                </div>
            </div> #}

            


            

    




            {# end body #}
           
        </div>
    </div>
</div>
{% endblock %}

templates/editor/model.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dashbord{% endblock %}

{% block body %}
{% if app.user %}


    {# structure de la page 10 colonnes de largeur et alignée à droite #}
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-10 col-lg-9 col-md-8 ml-auto mb-5 mt-5">

                {# page body #}
                {# {% include "template_parts/_nav_promotion.html.twig" %} #}










                {# end body #}

            </div>
        </div>
    </div>
{% endif %}
{% endblock %}