src/Entity/Apprenant.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ApprenantRepository")
 */
class Apprenant extends User
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    // /**
    //  * @ORM\Column(type="string", length=255)
    //  */
    // private $Email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Tel;

    /**
     * @ORM\Column(type="date")
     */
    private $DateNaissance;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Ville;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Git;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Avatar;

    



    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Reseau", mappedBy="Apprenant", orphanRemoval=true)
     */
    private $reseaux;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

  

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Offres", inversedBy="apprenant")
     */
    private $offres;

   

    /**
     * @ORM\OneToMany(targetEntity=PromoAppre::class, mappedBy="apprenant", orphanRemoval=true)
     */
    private $promoAppres;

    public function __construct()
    {

        $this->reseaux = new ArrayCollection();
        $this->promoAppres = new ArrayCollection();
    }

    public function getFullname()
    {
        return "{$this->Prenom} {$this->Nom}";
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    

    public function getTel(): ?string
    {
        return $this->Tel;
    }

    public function setTel(string $Tel): self
    {
        $this->Tel = $Tel;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->DateNaissance;
    }

    public function setDateNaissance(\DateTimeInterface $DateNaissance): self
    {
        $this->DateNaissance = $DateNaissance;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(string $Ville): self
    {
        $this->Ville = $Ville;

        return $this;
    }

    public function getGit(): ?string
    {
        return $this->Git;
    }

    public function setGit(?string $Git): self
    {
        $this->Git = $Git;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->Avatar;
    }

    public function setAvatar(?string $Avatar): self
    {
        $this->Avatar = $Avatar;

        return $this;
    }

    


    /**
     * @return Collection|Reseau[]
     */
    public function getReseaux(): Collection
    {
        return $this->reseaux;
    }

    public function addReseaux(Reseau $reseaux): self
    {
        if (!$this->reseaux->contains($reseaux)) {
            $this->reseaux[] = $reseaux;
            $reseaux->setApprenant($this);
        }

        return $this;
    }

    public function removeReseaux(Reseau $reseaux): self
    {
        if ($this->reseaux->contains($reseaux)) {
            $this->reseaux->removeElement($reseaux);
            // set the owning side to null (unless already changed)
            if ($reseaux->getApprenant() === $this) {
                $reseaux->setApprenant(null);
            }
        }

        return $this;
    }


    public function __toString()
    {
        return (string) strtoupper($this->Nom).' '.(string) strtoupper($this->Prenom);
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }


    public function getOffres(): ?Offres
    {
        return $this->offres;
    }

    public function setOffres(?Offres $offres): self
    {
        $this->offres = $offres;

        return $this;
    }

    

    /**
     * @return Collection|PromoAppre[]
     */
    public function getPromoAppres(): Collection
    {
        return $this->promoAppres;
    }

    public function addPromoAppre(PromoAppre $promoAppre): self
    {
        if (!$this->promoAppres->contains($promoAppre)) {
            $this->promoAppres[] = $promoAppre;
            $promoAppre->setApprenant($this);
        }

        return $this;
    }

    public function removePromoAppre(PromoAppre $promoAppre): self
    {
        if ($this->promoAppres->contains($promoAppre)) {
            $this->promoAppres->removeElement($promoAppre);
            // set the owning side to null (unless already changed)
            if ($promoAppre->getApprenant() === $this) {
                $promoAppre->setApprenant(null);
            }
        }

        return $this;
    }
}

src/Entity/Contacts.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ContactsRepository")
 */
class Contacts
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Tel;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Mobile;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Entreprise", inversedBy="Contact")
     */
    private $entreprise;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->Tel;
    }

    public function setTel(string $Tel): self
    {
        $this->Tel = $Tel;

        return $this;
    }

    public function getMobile(): ?string
    {
        return $this->Mobile;
    }

    public function setMobile(string $Mobile): self
    {
        $this->Mobile = $Mobile;

        return $this;
    }

    public function getEntreprise(): ?Entreprise
    {
        return $this->entreprise;
    }

    public function setEntreprise(?Entreprise $entreprise): self
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    public function getFullName()
    {
        return $this->Nom.' '.$this->Prenom;

    }
}

src/Entity/Offres.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OffresRepository")
 */
class Offres
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Intitule;

    /**
     * @ORM\Column(type="date")
     */
    private $DateDebut;

    /**
     * @ORM\Column(type="date")
     */
    private $DateFin;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $CahierDesCharges;

    

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Entreprise", inversedBy="offres")
     */
    private $Entreprise;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Apprenant", mappedBy="offres")
     */
    private $apprenant;

    public function __construct()
    {
        $this->apprenant = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIntitule(): ?string
    {
        return $this->Intitule;
    }

    public function setIntitule(string $Intitule): self
    {
        $this->Intitule = $Intitule;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->DateDebut;
    }

    public function setDateDebut(\DateTimeInterface $DateDebut): self
    {
        $this->DateDebut = $DateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->DateFin;
    }

    public function setDateFin(\DateTimeInterface $DateFin): self
    {
        $this->DateFin = $DateFin;

        return $this;
    }

    public function getCahierDesCharges(): ?string
    {
        return $this->CahierDesCharges;
    }

    public function setCahierDesCharges(?string $CahierDesCharges): self
    {
        $this->CahierDesCharges = $CahierDesCharges;

        return $this;
    }



    public function getEntreprise(): ?Entreprise
    {
        return $this->Entreprise;
    }

    public function setEntreprise(?Entreprise $Entreprise): self
    {
        $this->Entreprise = $Entreprise;

        return $this;
    }

    /**
     * @return Collection|Apprenant[]
     */
    public function getApprenant(): Collection
    {
        return $this->apprenant;
    }

    public function addApprenant(Apprenant $apprenant): self
    {
        if (!$this->apprenant->contains($apprenant)) {
            $this->apprenant[] = $apprenant;
            $apprenant->setOffres($this);
        }

        return $this;
    }

    public function removeApprenant(Apprenant $apprenant): self
    {
        if ($this->apprenant->contains($apprenant)) {
            $this->apprenant->removeElement($apprenant);
            // set the owning side to null (unless already changed)
            if ($apprenant->getOffres() === $this) {
                $apprenant->setOffres(null);
            }
        }

        return $this;
    }
}

src/Entity/Promotion.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PromotionRepository")
 */
class Promotion
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $Annee;

    /**
     * @ORM\Column(type="date")
     */
    private $DateDebut;

    /**
     * @ORM\Column(type="date")
     */
    private $DateFin;

    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Commentaires;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Formation", inversedBy="promotions")
     */
    private $Formation;


    /**
     * @ORM\OneToMany(targetEntity=PromoAppre::class, mappedBy="promotion",  orphanRemoval=true)
     */
    private $promoAppres;

    public function __construct()
    {

        $this->promoAppres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAnnee(): ?int
    {
        return $this->Annee;
    }

    public function setAnnee(int $Annee): self
    {
        $this->Annee = $Annee;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->DateDebut;
    }

    public function setDateDebut(\DateTimeInterface $DateDebut): self
    {
        $this->DateDebut = $DateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->DateFin;
    }

    public function setDateFin(\DateTimeInterface $DateFin): self
    {
        $this->DateFin = $DateFin;

        return $this;
    }



    public function getCommentaires(): ?string
    {
        return $this->Commentaires;
    }

    public function setCommentaires(?string $Commentaires): self
    {
        $this->Commentaires = $Commentaires;

        return $this;
    }

    public function getFormation(): ?Formation
    {
        return $this->Formation;
    }

    public function setFormation(?Formation $Formation): self
    {
        $this->Formation = $Formation;

        return $this;
    }

    

    public function __toString()
    {
        return (string) $this->Annee.' '.$this->Formation;
    }

    

    /**
     * @return Collection|PromoAppre[]
     */
    public function getPromoAppres(): Collection
    {
        return $this->promoAppres;
    }

    public function addPromoAppre(PromoAppre $promoAppre): self
    {
        if (!$this->promoAppres->contains($promoAppre)) {
            $this->promoAppres[] = $promoAppre;
            $promoAppre->setPromotion($this);
        }

        return $this;
    }

    public function removePromoAppre(PromoAppre $promoAppre): self
    {
        if ($this->promoAppres->contains($promoAppre)) {
            $this->promoAppres->removeElement($promoAppre);
            // set the owning side to null (unless already changed)
            if ($promoAppre->getPromotion() === $this) {
                $promoAppre->setPromotion(null);
            }
        }

        return $this;
    }

    
}

src/Entity/Reseau.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ReseauRepository")
 */
class Reseau
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Lien;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Apprenant", inversedBy="reseaux")
     */
    private $Apprenant;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getLien(): ?string
    {
        return $this->Lien;
    }

    public function setLien(string $Lien): self
    {
        $this->Lien = $Lien;

        return $this;
    }

    public function getApprenant(): ?Apprenant
    {
        return $this->Apprenant;
    }

    public function setApprenant(?Apprenant $Apprenant): self
    {
        $this->Apprenant = $Apprenant;

        return $this;
    }

    public function __toString()
    {
        return (string) $this->getNom();
    }
}

src/Form/PromotionType.php
<?php

namespace App\Form;

use App\Entity\Apprenant;
use App\Entity\Formation;
use App\Entity\Promotion;
use App\Repository\ApprenantRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

class PromotionType extends AbstractType
{
   
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Annee', IntegerType::class, [
                'attr' => array('min' => 2018, 'max' => 2030)

                ])

            ->add('DateDebut', DateType::class, [
                'widget' => 'single_text'
                ])

            ->add('DateFin', DateType::class, [
                'widget' => 'single_text',
                ])

            ->add('Commentaires')

            ->add('Formation', EntityType::class,[
                'class'=>Formation::class,
                'required'=>true,
                'label'=>'Selectionner la formation'
            ]) 

            ->add('apprenants',EntityType::class,[
                'class'=>Apprenant::class,
                'multiple' => true,
                'required' => false,
                'mapped'=>false,
                'label' => 'Attribuer des apprenants',
                'query_builder' => function (ApprenantRepository $er) {
                    return $er->createQueryBuilder('u')
                        ->where('u.status = :status')
                        ->setParameter('status', 'new')
                        ->orderBy('u.Nom');
                }
           
            ])
        ;

            
                
        
        }
       

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Promotion::class,
        ]);
    }
}

templates/editor/promotion/_collectionAppr.html.twig
{% block _promotion_apprenants_widget %}

{{ form_widget(form) }}

<input type="hidden" id="widgets-counter" value="0">
<div class="form-group">
    <button type="button" class="btn btn-info" id="add-apprenant">Ajouter un apprenant</button>

</div>

{% endblock %}

{% block _promotion_apprenants_entry_row %}

{{ form_widget(form) }}

{% endblock %}




{% block _promotion_apprenants_entry_widget %}

<div class="form-group" id="{{id}}">
    <div class="row">
        <div class="col-10">
            <div class="row">

                <div class="col">
                    {{ form_widget(form.Fullname) }}
                </div>
                {# <div class="col">
                    {{ form_widget(form.Prenom) }}
                </div> #}
            </div>
        </div>
        <div class="col-2">
            <button type="button" data-action="delete" data-target="#{{id}}" class="btn btn-danger">X</button>
        </div>
    </div>
</div>

{% endblock %}

templates/editor/promotion/apprenant_show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une Promotion{% endblock %}

{% block body %}
{% if app.user %}

<div class="container-fluid">
    <div class="row">
        <div class="col-xl-10 col-lg-9 col-md-8 ml-auto mb-5 mt-5">
            <!-- insert promotion navbar -->
            {% include "editor/promotion/_nav_promotion.html.twig" with {'p':1} %}

            <div class="my-5">
                <!-- un tableau d'un seul apprenant -->
                <h4 class="btn btn-info btn-sm">Fiche apprenant</h4>
                {% for apprenant in all %}
                <div class="row">
                    <div class="col-md-4">
            
                        <dl class="row">
                            <dt class="col-md-4"><img class="avatar"
                                    src="{{ asset('uploads/brochures/') }}{{apprenant.apprenant.avatar}}" alt=""></dt>
                            <dd class="col-md-8 pl-5">{{apprenant.apprenant.fullname|upper}}</dd>
                        </dl>
                    </div>
                    <div class="col-md-8 ">
                        <dl class="row">
                            <dt class="col-md-4">Git compte</dt>
                            <dd class="col-md-8">{{ apprenant.apprenant.git }}</dd>
                            <dt class="col-md-4">Email</dt>
                            <dd class="col-md-8">{{ apprenant.apprenant.email }}</dd>
                            <dt class="col-md-4">Adresse</dt>
                            <dd class="col-md-8">{{ apprenant.apprenant.adresse }}</dd>
                            <dt class="col-md-4">Ville</dt>
                            <dd class="col-md-8">{{ apprenant.apprenant.ville }}</dd>
                        </dl>
                    </div>
                </div>
            
                {% endfor %}
                <div>
            
                    <h6 class="show-liste btn-dark p-2">Formations</h6>
                    <table class="table table-hover">
            
                        <thead>
                            <th scope="col">N°</th>
                            <th scope="col">Annee</th>
                            <th scope="col">Début</th>
                            <th scope="col">Fin</th>
                            <th scope="col">N° d'heures</th>
                            <th scope="col">Intitulé</th>
            
            
                        </thead>
                        <tbody>
                            {% set i = 0 %}
                            {% for promotion in all %}
                            {% set i = i + 1 %}
            
                            <tr>
                                <td>{{i}}</td>
                                <td>{{ promotion.promotion.annee }}</td>
                                <td>{{ promotion.promotion.dateDebut|date("m/d/Y") }}</td>
                                <td>{{ promotion.promotion.dateFin|date("m/d/Y") }}</td>
                                <td>{{ promotion.promotion.formation.nombreHeure }}</td>
                                <td>{{ promotion.promotion.formation.intitule }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {# {% endif %} #}
                </div>
            
                <div>
                    {# si l'apprenant a des réseux sociaux #}
                    {% for reseau in all %}
            
            
                    {% if reseau.apprenant.Reseaux|length > 0 %}
                    <h6 class="show-liste btn-dark p-2">Réseaux Sociaux</h6>
                    <table class="table table-hover">
            
                        <thead>
                            <th scope="col">N°</th>
                            <th scope="col">Intitulé</th>
                            <th scope="col">Lien</th>
                        </thead>
                        <tbody>
                            {% set i = 0 %}
                            {% for reseau in reseau.apprenant.Reseaux %}
                            {% set i = i + 1 %}
                            <tr>
                                <td>{{i}}</td>
                                <td>{{reseau.nom}}</td>
                                <td>{{reseau.lien}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% endif %}
                    {% endfor %}
                </div>
            
                <div>
                    {# si l'apprenant a des retards #}
                    {% for retard in all %}
                    {% if retard.retards|length > 0 %}
                    <h6 class="show-liste btn-dark p-2">Retards</h6>
                    <table class="table table-hover">
                        <thead>
                            <th scope="col" style="width: 25%;">N°</th>
                            <th scope="col" style="width: 25%;">Date</th>
                            <th scope="col" style="width: 25%;">N° d'heures</th>
                            <th scope="col" style="width: 25%;">Justifié</th>
                        </thead>
                        <tbody>
                            {% set i = 0 %}
                            {% for retard in retard.retards %}
                            {% set i = i + 1 %}
                            <tr>
                                <td>{{i}}</td>
                                <td>{{retard.date|date('d/m/y')}}</td>
                                <td>{{retard.nombreheure}}</td>
                                <td>{{retard.justifie}}</td>
            
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% endif %}
                    {% endfor %}
                </div>
            
                <div>
                    {# si l'apprenant a des absences #}
                    {% for absence in all %}
                    {% if absence.absences|length > 0 %}
                    <h6 class="show-liste btn-dark p-2">Absences</h6>
                    <table class="table table-hover">
                        <thead>
                            <th scope="col" style="width: 25%;">N°</th>
                            <th scope="col" style="width: 25%;">Date de début</th>
                            <th scope="col" style="width: 25%;">Date de fin</th>
                            <th scope="col" style="width: 25%;">Justifié</th>
                        </thead>
                        <tbody>
                            {% set i = 0 %}
                            {% for absence in absence.absences %}
                            {% set i = i + 1 %}
                            <tr>
                                <td>{{i}}</td>
                                <td>{{absence.dateDebut|date('d/m/y')}}</td>
                                <td>{{absence.datefin|date('d/m/y')}}</td>
                                <td>{{absence.justifie}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% endif %}
                    {% endfor %}
            
                </div>
            
                <div>
                    <h6 class="show-liste btn-dark p-2">Fiche Profil</h6>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

{% block javascripts %}

{% endblock %}

templates/editor/promotion/promo_attr.html.twig
{% extends 'base.html.twig' %}

{% block title %}Attribuer un apprenant{% endblock %}

{% block body %}
{% if app.user %}

<div class="container-fluid">
    <div class="row">
        <div class="col-xl-10 col-lg-9 col-md-8 ml-auto mb-5 mt-5">

            {% include "editor/promotion/_nav_promotion.html.twig" with {'p':3} %}

            {# pour afficher le flash message #}
            <div class="my-5">
                
                <h4 class="btn btn-info btn-sm">Attribuer un apprenant</h4>
                {{ form_start(form) }}
                {{ form_widget(form) }}
                
                <button class="btn btn-outline-danger d-block ml-auto">Enregistrer</button>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/editor/promotion/promo_show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Afficher une promotion{% endblock %}

{% block body %}
{% if app.user %}

    <div class="container-fluid" >
        <div class="row">
            <div class="col-xl-10 col-lg-9 col-md-8 ml-auto mb-5 mt-5">

                {% include "editor/promotion/_nav_promotion.html.twig" with {'p':1} %}

                <div class="my-5">
                   
                    <h4 class="btn btn-info ">Afficher une Promotion </h4>

                    <!-- afficher une seule promotion -->

                    <div class="col my-5">
                        <dl class="row">
                            <dt class="col-md-2">Année</dt>
                            <dd class="col-md-4">{{ promotion.annee }}</dd>
                            <dt class="col-md-2">Formation</dt>
                            <dd class="col-md-4">{{ promotion.formation.intitule }}</dd>
                            <dt class="col-md-2">Date de début</dt>
                            <dd class="col-md-4">{{ promotion.dateDebut|date("d/m/Y") }}</dd>
                            <dt class="col-md-2">Date de fin</dt>
                            <dd class="col-md-4">{{ promotion.dateFin|date("d/m/Y") }}</dd>
                        </dl>
                    </div>

                    {# liste des apprenants appartenant à une promotion #}
                    <table class="table ">
                     
                        <thead>
                            <th scope="col" style="width: 10%;">N°</th>
                            <th scope="col" style="width: 18%;">Nom et Prénom</th>
                            <th scope="col" style="width: 18%;">Email</th>
                            <th scope="col" style="width: 18%;">Git compte</th>
                            <th scope="col" style="width: 18%;">Avatar</th>
                            <th scope="col" style="width: 18%;">Actions</th>
                        </thead>
                        <tbody>
                        
                            {% set i = 0 %}
                            {% for apprenant in apprenants %}
                            {% set i = i + 1 %}
                            <tr>
                                <td>{{i}}</td>
                                <td>{{ apprenant.apprenant.FullName }}</td>
                                <td>{{ apprenant.apprenant.email }}</td>
                                <td>{{ apprenant.apprenant.git }}</td>
                                <td><img src="{{ asset('uploads/brochures/') }}{{ apprenant.apprenant.avatar }}" alt="" class="avatar-sd"></td>
                            
                                <!-- un lien pour afficher un apprenant-->
                                <td><a class="btn btn-info btn-sm modif_promotion" title="visualiser"
                                        href="{{ path('editor_pro_apprenant_show',{'id':apprenant.apprenant.id}) }}"><i class="fa fa-eye"></i></a>

                                    <a class="btn btn-danger btn-sm delete-record my-1" title="retirer" href="#"><i
                                            class="fas fa-trash-alt delete-promotion"></i></a>

                                    {# delete confirmation #}
                                    <div class="delete-confirm border bg-light  m-auto rounded p-3" style="position: absolute;top:40%;left:30%">
                                        <div>
                                            <h4>Vous êtes sûr de vouloir supprimer?</h4>
                                        </div>
                                        <div>
                                            <a class="btn btn-success non" href="">Non</a>
                                            <a class="btn btn-danger " href="{{ path('editor_retirer_apprenant',{'id':apprenant.id}) }}">Oui</a>
                                    
                                        </div>
                                    </div>
                                    {# end delete confirmation #}
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>   
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endif %}
{% endblock %}